services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: staj1_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    expose:
      - 9000
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: staj1_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:16-alpine  # Burada postgres imajını belirtiyoruz
    container_name: staj1_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
